etmem: Fix two minor issues that prevented compilation when PMU is enabled
I ran into the following issues when building with -DENABLE_PMU=ON option,

---------------------------------------------------------------------
[ 14%] Building C object etmem/CMakeFiles/etmemd.dir/src/etmemd_src/etmemd_slide.c.o
/root/dev/etmem/etmem/src/etmemd_src/etmemd_slide.c: In function ‘slide_executor’:
/root/dev/etmem/etmem/src/etmemd_src/etmemd_slide.c:230:36: error: expected ‘)’ before ‘{’ token
  230 |     if ((slide->pmu_params == NULL) {
      |        ~                           ^~
      |                                    )
---------------------------------------------------------------------

removing the extra parentheses solves the problem.  After fixing it, I found
another compilation error,

---------------------------------------------------------------------
[  3%] Building C object etmem/CMakeFiles/etmemd.dir/src/etmemd_src/etmemd_cslide.c.o
/root/dev/etmem/etmem/src/etmemd_src/etmemd_cslide.c: In function ‘fill_vma_updata_rate’:
/root/dev/etmem/etmem/src/etmemd_src/etmemd_cslide.c:2216:9: error: ‘params’ undeclared (first use in this function); did you mean ‘pmu_params’?
 2216 |     if (params->pmu_params == NULL) {
      |         ^~~~~~
      |         pmu_params
/root/dev/etmem/etmem/src/etmemd_src/etmemd_cslide.c:2216:9: note: each undeclared identifier is reported only once for each function it appears in
/root/dev/etmem/etmem/src/etmemd_src/etmemd_cslide.c: At top level:
/root/dev/etmem/etmem/src/etmemd_src/etmemd_cslide.c:2226:12: error: redefinition of ‘fill_vma_updata_rate’
 2226 | static int fill_vma_updata_rate(void *obj, void *val)
      |            ^~~~~~~~~~~~~~~~~~~~
/root/dev/etmem/etmem/src/etmemd_src/etmemd_cslide.c:2214:12: note: previous definition of ‘fill_vma_updata_rate’ with type ‘int(void *, void *)’
 2214 | static int fill_vma_updata_rate(void *obj, void *val)
      |            ^~~~~~~~~~~~~~~~~~~~
/root/dev/etmem/etmem/src/etmemd_src/etmemd_cslide.c:2214:12: error: ‘fill_vma_updata_rate’ defined but not used [-Werror=unused-function]
cc1: all warnings being treated as errors
---------------------------------------------------------------------

The root cause of this reported error is the redefined fill_vma_updata_rate
function, and this patch removes the redundant one.

After submitting this patch, the openeuler-ci-bot pointed out that the
slide_executor function was too long.  Therefore, this patch also reduces
the length of the function.

Tested by rebuilding on x86_64 openEuler 20.03, 22.03 and 24.03.

Fixes: 012fec939e77 ("Adapt PMU sampling function to cslide")
Signed-off-by: Enze Li <lienze@kylinos.cn>