memRouter: test: Add missing header file
Without this patch, GCC warns,

---------------------------------------------------------------------
In file included from /usr/include/CUnit/Automated.h:41:0,
                 from /root/dev/etmem/memRouter/test/Unit/memdcd_threshold_llt_test/memdcd_threshold_llt.c:18:
/root/dev/etmem/memRouter/test/Unit/memdcd_threshold_llt_test/memdcd_threshold_llt.c: In function ‘test_memdcd_threshlod’:
/root/dev/etmem/memRouter/test/Unit/memdcd_threshold_llt_test/memdcd_threshold_llt.c:67:57: warning: implicit declaration of function ‘getpid’; did you mean ‘getpt’? [-Wimplicit-function-declaration]
     CU_ASSERT_EQUAL(threshold_policy_opt->parse(policy, getpid(), pages, &pages_to_numa, &pages_to_swap), 0);
                                                         ^
...

/root/dev/etmem/memRouter/test/Unit/memdcd_policy_llt_test/memdcd_policy_llt.c: In function ‘test_memdcd_policy’:
/root/dev/etmem/memRouter/test/Unit/memdcd_policy_llt_test/memdcd_policy_llt.c:60:5: warning: implicit declaration of function ‘chown’ [-Wimplicit-function-declaration]
     chown("./config/policy_threshold_invalid_unit_str.json", 1, 1);
     ^~~~~
---------------------------------------------------------------------

Although it doesn't have much impact, it's better to squash them anyway.

Tested by rebuilding on x86_64 openEuler 20.03, 22.03 and 24.03.

Signed-off-by: Enze Li <lienze@kylinos.cn>