etmem: Fix a building issue caused by undefined fill_engine_type_psi_fb
I ran into the following error one by one while buiding test cases,

---------------------------------------------------------------------
[ 43% ] Linking C executable bin/etmemd
/usr/bin/ld:
CMakeFiles/etmemd.dir/root/dev/etmem/etmem/src/etmemd_src/etmemd_engine.c.o:(.data.rel+0x78):
undefined reference to `fill_engine_type_psi_fb'
collect2: error: ld returned 1 exit status

......

[ 95% ] Linking C executable ../bin/etmem_cslide_ops_llt
/usr/bin/ld: /root/dev/etmem/etmem/test/build/lib/libcslide_dep.so:
undefined reference to `fill_engine_type_psi_fb'
collect2: error: ld returned 1 exit status
---------------------------------------------------------------------

after some digging, I found that the root cause of this issue was that,
from this commit,

  commit 1a5fd89106c82be3f40cc69dc1f09d88c46f63ec
  Date:   Fri Aug 18 14:27:25 2023 +0800

      etmem: Use the psi feature to perform cgroup-based swap.

the necessary items were missing from the CMakeLists.txt file,
resulting in the etmemd_psi_fb module not participating in the compilation.

Tested on both openEuler 20.03 and 22.03.

Signed-off-by: Enze Li <lienze@kylinos.cn>